package ch.duong.jmd.#APP_ABBREVIATION.entity.enumeration;

public enum AppConfigurationKey {
    ADMIN_USERNAME,
    ADMIN_PASSWORD,
    ADMIN_ROLE,
    LDAP_URL_1,
    LDAP_URL_2,
    LDAP_BASE_DN,
    LDAP_CONNECT_TIMEOUT,
    INTERVENTION_END_OFFSET,
    DOCUMENT_BASE_FOLDER_PATH,
    DOCUMENT_BASE_FOLDER_NAME,
    DOCUMENT_AUTHORIZE_TYPE,
    DOCUMENT_THUMBNAIL_WIDTH,
    DOCUMENT_THUMBNAIL_HEIGHT,
    DOCUMENT_MAX_SIZE,
    DIRECTORY_MAX_SIZE,
    NOTIFICATION_ADMIN_ERROR_EMAILS,
    MAIN_REPORT_MODEL
}
